version: '3'
services:
  php:
    working_dir: /var/www/php
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/var/www/php
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - php

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: slido
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: xraffay
      MYSQL_PASSWORD: xQt@z
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db.cnf:/etc/mysql/conf.d/my.cnf
      - ./Slido.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server:/var/www/php
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro  # Mount SSL certificates
    depends_on:
      - php