version: '3'
services:
  php:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - php

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: slido
      MYSQL_USER: xraffay
      MYSQL_PASSWORD: xQt@z
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db.cnf:/etc/mysql/conf.d/my.cnf